### ISSUE TITLE
Develop the DB architecture

### ISSUE THREAD

**Issue by ldemk** [ldemk/assistant#1]
We will use the [Google Firebase](https://firebase.google.com/) DB.

**Comment by v-lavrushko** [comment]
Do we need to create it or just learn how to use it?

**Comment by ldemk** [comment]
I guess we might use it for the project. We need to store the data somewhere.

**Comment by deathtanks** [comment]
Project ‘Turtle bot’ has next architecture: 
1.User firstly goes through authorization as an employee in SoftServe. 
2.Then point name. 
3.After note location of office (country, city, etc) a location of user in office ( floor, room, workplace). By this information defines coordinates, and turtle bot begins movement by this coordinates.
[TurtleBot.pdf](https://github.com/ldemk/assistant/files/2521624/TurtleBot.pdf)

**Comment by ldemk** [comment]
Nice initial document.
Here are some links that may help You to develop the structure of DB
[link#1](https://firebase.google.com/docs/database/android/structure-data#best_practices_for_data_structure), [link#2](https://proandroiddev.com/working-with-firestore-building-a-simple-database-model-79a5ce2692cb), [link#3](https://www.sitepen.com/blog/2010/05/11/nosql-architecture/), [link#4](https://highlyscalable.wordpress.com/2012/03/01/nosql-data-modeling-techniques/)

**Comment by ldemk** [comment]
Please, provide, the JSON structure of DB and  mind the connections between documents

**Comment by deathtanks** [comment]
[Turtle_diagram.pdf](https://github.com/ldemk/assistant/files/2572463/Turtle_diagram.pdf)

**Comment by deathtanks** [comment]
![turtle2](https://user-images.githubusercontent.com/33390278/48697524-7d7e3600-ebed-11e8-90e0-893c8c6c5dc2.png)

**Comment by deathtanks** [comment]
![2018-11-19 12-24-27](https://user-images.githubusercontent.com/33390278/48702404-85dc6e00-ebf9-11e8-86ac-a5ef9600c692.png)

**Comment by deathtanks** [comment]
![data](https://user-images.githubusercontent.com/33390278/49159258-c12f1900-f32c-11e8-9f62-a305fe329916.jpg)

**Comment by sofiia-tesliuk** [comment]
### Employees ###

```
{
    "employees": {
        "name_surname": {
            "is_available": "bool",
            "location_id": "location id"
        }
    }

    "locations_id": {
        "location id": {
            "coordinate_id": "coordinate id",
            "info": {
                "floor": "floor",
                "office": "name of office",
                "workplace": "number of workplace"
            }
        }
    }

    "coordinates_id": {
        "coordinate id": {
            "x": "x coordinate",
            "y": "y coordinate"
        }
    }
}
```

<br  />

### Authentication ###

```
{
    "users": {
        "username": {
            "privilege": "admin"/"guest",
            "password_id": "password id",
            "valid_date_id": "valid date id"
        }
    }

    "passwords_id": {
        "password id": {
            "password": "user password"
        }
    }

    "valid_dates_id": {
        "valid date id": {
            "from": "DD/MM/YYYY"
            "to": "DD/MM/YYYY"
        }
    }
}
```
